spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/charitywebsite
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: hoa0976271476
  springdoc:
    swagger-ui:
      enabled: true
      path: /swagger-ui.html
    api-docs:
      enabled: true